name: Run Crypto Signal Bot every 15 min

on:
  schedule:
          # Runs at 06:00, 09:00, 12:00, and 15:00 UTC (09:00, 12:00, 15:00, and 18:00 Athens)
        - cron: '0 6 * * *'
        - cron: '0 9 * * *'
        - cron: '0 12 * * *'
        - cron: '0 15 * * *'5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas ta requests python-telegram-bot==13.15

      - name: Run bot
        run: python crypto_signal_bot.py

